title: Jeremiah Inyiama
logo: /assets/img/Headshot.png
description: IT Support Specialist focused on systems reliability, networking, and cloud fundamentals, with growing experience in automation and DevOps practices
theme: jekyll-theme-minimal
