title: Jeremiah Inyiama
logo: /assets/img/Headshot.png
description: "ğŸ’» GitHub: [Jerriemiah](https://github.com/Jerriemiah) Â· ğŸ’¼ LinkedIn: [Profile](https://www.linkedin.com/in/...) Â· ğŸ“§ [Email](mailto:inyiamajeremiah@gmail.com)"
theme: jekyll-theme-minimal
