title: Jeremiah Inyiama
logo: /assets/img/Headshot.png
#description: "[![Gmail](https://skillicons.dev/icons?i=gmail)](mailto:Inyiamajeremiah@gmail.com)" "[![Linkedin](https://skillicons.dev/icons?i=linkedin)](https://www.linkedin.com/in/jeremiah-inyiama/)" "[![GitHub](https://skillicons.dev/icons?i=github)](https://github.com/Jerriemiah)"
theme: jekyll-theme-minimal
